name: 'Issue-Assigner Bot'
description: 'Automates rule-based assignment of issues to users based on comments'
author: 'SohamRatnaparkhi'

branding:
  icon: 'git-pull-request'
  color: 'blue'

inputs:
  roles-config-inline:
    description: 'Inline YAML string for defining roles and their rules.'
    required: false
  roles-config-path:
    description: 'Path to an external YAML file with roles and their rules.'
    required: false
    default: ''
  issue-states-inline:
    description: 'Inline YAML string for defining issue states and corresponding labels.'
    required: true
  maintainers-config:
    description: 'Path to the maintainers configuration file.'
    required: true
    default: 'maintainers.yml'
  gh-token:
    description: 'GitHub token for authentication purposes.'
    required: true

outputs:
  assignment-status:
    description: 'Provides the status of the issue assignment process.'

runs:
  using: 'node20'
  main: 'dist/index.js'
