name: 'Issue-Assigner Bot'
description:
  'Automatically assigns issues to users based on issue comments and
  configurable rules.'
author: 'Soham Ratnaparkhi'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  roles-config-inline:
    description:
      'Inline YAML string defining roles and rules. Will be used if config-path
      is not provided.'
    required: false
  config-path:
    description:
      'Optional: Path to an external YAML configuration file defining roles,
      rules, and states. Overrides roles-config-inline if provided.'
    required: false
    default: ''
  issue-states-inline:
    description:
      'Inline YAML string defining the issue states and corresponding labels.'
    required: true
  maintainers-config:
    description: 'Path to the maintainers configuration file.'
    required: true
    default: 'maintainers.yml'
  gh-token:
    description: 'GitHub token with permissions to manage issues and assignees.'
    required: true

outputs:
  assignment-status:
    description: 'Status of the issue assignment process.'

runs:
  using: 'node20'
  main: 'dist/index.js'
