name: Issue Assignment Workflow

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, reopened, closed, converted_to_draft, ready_for_review, review_requested, review_request_removed]

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
      
      - name: Assign Issue
        uses: ./ # Path to your custom action
        with:
          roles-config-inline: |
            admin:
              max-assigned-issues: 10
              max-opened-prs: 5
              unassign-others: true
              allowed-labels: "label1,label2,label3,label4"
            maintainer:
              max-assigned-issues: 5
              max-opened-prs: 3
              unassign-others: false
              allowed-labels: "label3,label4"
            developer:
              max-assigned-issues: 2
              max-opened-prs: 1
              unassign-others: false
              allowed-labels: "label1,label2"
            default:
              max-assigned-issues: 1
              max-opened-prs: 0
              unassign-others: false
              allowed-labels: "label1"
          issue-states-inline: |
            ready-for-assignment: help-wanted
            assigned: taken
            in progress: worked-on
            in-review: review
            done: closed
          maintainers-config: 'maintainers.yml'
          gh-token: ${{ secrets.GITHUB_TOKEN }}
