name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
      - name: Assign Issue
        uses: ./ # Path to your custom action
        with:
          roles-config-inline: |
            admin:
              max-assigned-issues: 10
              max-opened-prs: 5
              unassign-others: true
              allowed-issue-states: ready-for-assignment, assigned, in progress, in-review
            maintainer:
              max-assigned-issues: 5
              max-opened-prs: 3
              unassign-others: true
              allowed-issue-states: ready-for-assignment, assigned, in progress, in-review
            developer:
              max-assigned-issues: 2
              max-opened-prs: 1
              unassign-others: false
              allowed-issue-states: ready-for-assignment, assigned, in progress
            default:
              max-assigned-issues: 1
              max-opened-prs: 0
              unassign-others: false
              allowed-issue-states: ready-for-assignment
          issue-states-inline: |
            ready-for-assignment: help-wanted
            assigned: taken
            in progress: worked-on
            in-review: review
            done: closed
          maintainers-config: 'maintainers.yml'
          gh-token: ${{ secrets.GITHUB_TOKEN }}
